<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Run all test cases</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>7bf97982-ee23-41ac-bda0-b682064855b8</testSuiteGuid>
   <testCaseLink>
      <guid>6ad16daa-a814-498d-923c-fc4ca7809e60</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/csv test case/private-channel</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06b790d4-652e-4e66-aac3-7e73446f4fc0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ffee64fa-3701-49a3-97d0-aff0825351e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8fa85ab-5130-4933-ab43-c77b263d0ff0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>36899ca0-00e8-49dd-a253-c09e38884350</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/csv test case/public-channel</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16b924fc-1ead-46ad-b6c4-b93753cae64a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e07870b2-eb96-4de1-bdc8-880f925ded2b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7db604c0-56c2-437c-a695-c1b8a37a0793</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6c69cae9-76d9-4845-ac24-a3c3bb3a91de</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/csv test case/login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69ae59bc-bc6e-4ff7-bf09-d5e32ef94317</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>301414b8-ca87-440c-8430-c6fc3ab61177</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>068f9ee8-865f-48f5-ab67-7bc6242a11f6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/csv test case/direct-message</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6394f847-354b-44e9-8737-bd25c247ab87</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e13f0343-4026-466a-9687-bf1d51044e10</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/csv test case/full-name</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>425a9250-e1ef-4732-9d0d-63dfead653bc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>797d51a4-163f-4c19-99d5-5b63fd5a4446</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fa0f1993-e0ba-41a4-b272-fb88e1297c30</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/internal data test case/email</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc112188-0ffb-49a8-9d0d-e55f8033c2b3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>504a5b2e-f4f1-47bc-88fb-ccde0fb59b62</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a93c44cb-2ac0-4078-9be9-fcd8aea0ef75</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>35c0d7be-06fd-49e6-8959-ab83f54508dd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/internal data test case/word-trigger</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cbb1658c-2fad-4fa6-b039-08cea0b5a67b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c3236d59-d737-47a8-8404-f0e4117e9b8c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/internal data test case/private-channel</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06b790d4-652e-4e66-aac3-7e73446f4fc0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ffee64fa-3701-49a3-97d0-aff0825351e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8fa85ab-5130-4933-ab43-c77b263d0ff0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ebadd532-a64e-4266-95d0-b3472f3e7f91</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/internal data test case/emotion</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>472f998e-07c1-4c1c-8a7d-bfa754462722</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9937a24b-4c8c-412a-9e25-1605dfb01a66</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/internal data test case/username</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a38ae5b4-39f4-4436-973e-430ec46fa8a4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6df5e3b2-76d7-4753-8b28-d3f9d17b7a01</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/internal data test case/public-channel</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16b924fc-1ead-46ad-b6c4-b93753cae64a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e07870b2-eb96-4de1-bdc8-880f925ded2b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7db604c0-56c2-437c-a695-c1b8a37a0793</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6024ee85-2f79-4f5b-8577-cad87a7e8452</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/internal data test case/login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69ae59bc-bc6e-4ff7-bf09-d5e32ef94317</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>301414b8-ca87-440c-8430-c6fc3ab61177</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0b130c34-a039-4a30-b00d-9c93066a8460</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/internal data test case/direct-message</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6394f847-354b-44e9-8737-bd25c247ab87</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d611a8fe-a0bf-4d4c-a24e-f303ffdec1e7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/internal data test case/header</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0617c1d2-6429-4147-81f0-082263a832e2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5cad814a-8887-4469-b03b-6bc9c8a90502</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/internal data test case/nickname</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d5d59a38-8604-485d-b2e8-15a4669d621e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>85ae4bd5-bb21-4045-88ac-eae46bf09175</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/internal data test case/language</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e264a721-76b8-4347-a6ff-f0dbdadf0d11</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f357ac34-3416-45dc-87e6-419ec609aa65</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/internal data test case/position</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>77eb1309-f0b2-4469-ad4d-d5ffa962c892</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9300d9f0-e2c0-4969-9bca-835dc8e8f799</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/internal data test case/password</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa7e0dd9-4c82-4453-8275-99fa1fab2156</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e18cae49-7008-496f-8674-99543b3ca20b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76c5028b-5c46-4a92-a0b0-3bd518719cef</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4386cd5e-ccfd-4744-b572-57c69fe2ba8b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/internal data test case/search</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba6f8419-8c61-4c05-8db5-abe2fcbd48f3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f3585109-58ea-4acc-91e3-4e89686a509a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/internal data test case/full-name</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>425a9250-e1ef-4732-9d0d-63dfead653bc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>797d51a4-163f-4c19-99d5-5b63fd5a4446</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>53521368-e075-400f-9ffe-debf93a7d030</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Logout</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>4644eec3-f3e4-440f-883c-58320c305294</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Create_public_channel</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1f15a39a-4f81-4407-9bcf-ae0aa6dbf3b4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8df5747d-0b08-4cfb-a40b-8a03c9125727</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a58b0897-0c9f-4a92-84f4-9618090382a8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a37cb1a8-bcfa-452a-bb17-6fbed42679bb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Create_private_channel</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>78fe5019-7094-443c-b8c5-549be15db572</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7669d5ad-fedd-4259-945a-e9c7a664e434</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1dc9f2e7-b33c-41f3-a3e7-17ff10cb14ca</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e26ddbca-64d6-450c-b00a-27eeb5f787ad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Create_team</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f780ce6-1ca5-45ce-90ee-77e99c2317d9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1f459a20-6253-4148-983f-885121f14053</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UI/Login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>19034dcb-e1e1-4d18-b699-85d6079296fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a476d669-3e7e-427c-aaae-14db8eea32ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b959627-bfff-4448-bf0f-4140c0927ec8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>16d6547b-e21e-473c-9865-3b5cd376a602</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Use condition/Message_public_channel</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0df7305b-b27a-4253-b886-c31cfbcdbc5e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a8f439f2-45f5-4db5-b9e3-0c585af02ae8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Use condition/Create_public_channel</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0050ff8e-f2be-40ce-bc10-a7d0bacbbd4e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e92827a-9b0f-43dd-818e-504c69b1f464</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>223daf8e-b8ae-424b-a1a6-4da488737af1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>690c6555-a487-44af-8527-20278ee35540</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Use condition/Create_private_channel</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>072de47d-2ad0-4dee-a93b-8233f0a2fc75</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9eb6b935-b717-41bb-b397-3152369d0b08</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c1cbfe2-1ca1-4384-9ae6-d92cc238a55f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0008febc-6f4e-4709-82e8-e2f3f68a75da</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Use condition/Create_team</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9f345d6-7d43-4af5-8622-5c53143ba510</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>667faf4b-4fab-45ef-a45a-1a47d7ed2399</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Use condition/Login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3b069c7-e972-485a-84cd-9e7a364f3997</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>794e4b76-3018-490e-960f-d094712dfb81</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e55416aa-964e-453d-88e6-9819886c915d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3ab01911-3e42-40ef-bad6-239e8e19b3a7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Use loop/Message_public_channel</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11fb4f69-92d9-48f9-aad7-0702fd634d9b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>13a69dd0-1031-41f9-8c14-b23cfe290f4f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Use loop/Message_private_channel</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2b76794-7c1b-4fe9-b1c5-c921c4ecb474</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e0567853-0522-477e-bcbb-f836f3f9ca4f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Use loop/Edit-message</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae282ece-c9d2-47ce-b60d-c29ecaf16d9f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6ab00ddc-d27e-4030-9716-daf4318eae85</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Use loop/Reply_message</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3713024a-45a5-4bc1-883d-c53e6d1b7dda</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>342a7621-1f14-4521-b31f-38e4ce4ffc91</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Use loop/Direct_message</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a03957e2-8cc3-4009-96a7-ba64f9f63e35</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e7a81da9-bf71-4819-9ca4-caaf2d12353a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Switch case/Search_comment</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85c4eb90-7055-4250-8296-b61b755621fb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b16471b6-3754-434f-bba6-b7c6f6206ad7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Switch case/Change_channel</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce8ea255-4ee6-4cd8-b66e-105e72b0d8c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>587a2dc0-3cec-4e76-b2c9-0f69e933e9f3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62419005-ed4a-4fcb-a0aa-44daafff78c2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f26709c4-e0fe-42a8-b30a-e5c916e60057</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Switch case/Login_fail</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fbc18fb6-aa8c-43c2-9730-ea3fe4a590df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>297dc17e-c688-4cfa-b063-ca3b178db1b3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>df043c81-797c-410c-81b1-6ae29836a72c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Switch case/New_comment</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>78443e66-3eb5-405e-8aab-9841847ab56b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>40112532-f316-41a8-b398-445db8936ce8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Switch case/Login_success</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f88f5170-3c27-4059-9e68-87f652badcf0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c123c7ef-2603-4991-bfac-2d281f068253</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dd0dcdf1-369b-4c81-880b-a4a774e5578c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Call Other/Create_channel</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d43a6f94-5b5a-48f2-8364-551553a6e7f8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>78db2700-def2-43e1-b113-87edcfc05c18</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Call Other/Login_logout</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>40b283d1-1a96-46b4-88d4-54282d047860</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Call Other/New_comment</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>6b1007f3-c8b1-4f4a-841d-df8143a60108</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Call Other/Edit_fullname</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>c5578388-c042-49f8-8395-2e711d76c49d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Call Other/Change_channel_and_add_comment</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
