<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>login-csv</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>8afcc3ce-350c-48da-ad93-b55384357e5f</testSuiteGuid>
   <testCaseLink>
      <guid>0978ca39-9710-4c31-b54e-caa5586b96eb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/csv test case/login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>2ee80687-3d96-4aff-853d-397b8d2704da</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/csv/login</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>2ee80687-3d96-4aff-853d-397b8d2704da</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>﻿username</value>
         <variableId>69ae59bc-bc6e-4ff7-bf09-d5e32ef94317</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2ee80687-3d96-4aff-853d-397b8d2704da</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>301414b8-ca87-440c-8430-c6fc3ab61177</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
